name: Test Properties

on: 
  pull_request:
    branches:
      -main
  push:
    branches:
      -main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-auto-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install pytest

    - name: Run Tests
      run: pytest db-url-check.py
