name: Test Properties

on: [push, pull_request]

jobs:
  build:
    name: Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install pytest

    - name: Run Tests
      run: pytest db-url-check.py
